name: ASP.NET Azure DevOps Octopus Built-in Feed TFVC Video
on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '0 0 18 * *'
jobs:
  build:
    if: (github.event_name != 'repository_dispatch') || (github.event.client_payload.workflow == github.workflow) || (github.event.client_payload.workflow == 'all') || (github.event.client_payload.workflow == 'azuredevops-aspnet-video')
    runs-on: windows-2019
    env:
      SMTP_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
      WISTIA_USERNAME: ${{ secrets.WISTIA_USERNAME }}
      WISTIA_PASSWORD: ${{ secrets.WISTIA_PASSWORD }}
      MEDIA_PATH: C:\screenshots
      CUCUMBER_TAGS: "(not @browserspecific or @firefox) and (not @destinationspecific or @iis) and (not @repositoryspecific or @octo-built-in-feed) and (not @applicationspecific or @aspnet) and (not @sourcespecific or @tfvc)"
      WISTIA_MEDIA_ID: yhutvs36se
      DISABLE_HIGHLIGHTS: true
      DISABLE_SCREENSHOTS: true
      MOVE_TO_MOUSE_CUSROR: true
      MOUSE_VERTICAL_OFFSET: 74
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes-aspmvc4.git
      NUGET_PATH: 'RandomQuotes\obj\octopacked\'
      VIDEO_FILE_NAME: aspnet-azuredevops-octopus-builtin-feed-tfvc.mp4
      SCREENSHOT_PATH:
    steps:
    - uses: actions/checkout@v1

    - name: Set screen resolution
      shell: powershell
      run: ./scripts/windows/set-lowresolution.ps1

    - name: Free some space
      shell: powershell
      run: ./scripts/windows/free-space.ps1

    - name: Disable Windows Defender
      shell: powershell
      run: reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' /v DisableRealtimeMonitoring /t REG_DWORD /d 1

    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts sqlserverexpress.pp,azuredevops.pp,azuredevopsagent.pp,utilities.pp,dotnetutilities.pp,octopus.pp,iis.pp,sleep.pp,azurewait.pp

    - name: Create API key
      shell: powershell
      run: ./scripts/windows/create-apikey.ps1

    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\octopus-api-key.pp --disable_warnings=deprecations'

    - name: Add project
      shell: powershell
      run: ./scripts/windows/azuredevops-create-project-tfvc.ps1

    - name: Populate TFVC repo
      shell: powershell
      run: ./install.ps1 -Scripts sqlserverexpress.pp,azuredevopstfvcaspnet.pp

    - name: Run the build
      shell: powershell
      run: ./scripts/windows/azuredevops-continue-project-tfvc.ps1

    - name: Create the Octopus Environments
      shell: powershell
      run: ./scripts/windows/create-environments.ps1

    - name: Add tentacle
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\tentacle.pp --disable_warnings=deprecations'

    - name: Create Octopus Project
      shell: powershell
      run: ./scripts/windows/create-octopusaspnetproject.ps1

    - name: Open Random Quotes
      shell: powershell
      run: ./scripts/windows/open-iisdevapp.ps1

    - name: Add a deployment step
      shell: powershell
      run: ./scripts/windows/azuredevops-create-deployment.ps1

    - name: Shutdown Azure Devops
      shell: powershell
      run: ./scripts/windows/stop-azuredevops.ps1

    - name: Add a lifecycle
      shell: powershell
      run: ./scripts/windows/create-lifecycle.ps1

    - name: Open Random Quotes in the test environment
      shell: powershell
      run: ./scripts/windows/open-iistestapp.ps1

    - name: Add manual intervention
      shell: powershell
      run: ./scripts/windows/add-manualintervention.ps1

    - name: Add email notification
      shell: powershell
      run: ./scripts/windows/add-notification.ps1

    - name: Add users and team
      shell: powershell
      run: ./scripts/windows/create-usersandteams.ps1

    - name: View internal deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-internaldeployerdashboard.ps1

    - name: View production deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-productiondeployerdashboard.ps1

    - name: View audit logs
      shell: powershell
      run: ./scripts/windows/view-auditlogs.ps1

    - name: Process video
      shell: powershell
      run: ./scripts/windows/process-video.ps1

    - name: Upload video
      shell: powershell
      run: ./scripts/windows/upload-video.ps1

    - name: Replace Wistia Video
      shell: powershell
      run: ./scripts/windows/replace-wistia-video.ps1

